### ISSUE TITLE
Fix in documentation

### ISSUE THREAD

**Issue by yuravake** [filipealva/PickerView#12]
Small fix in documentation :
"And the title for each row:
func pickerView(pickerView: PickerView, titleForRow row: Int, index: Int) -> String {
    let item = itemsThatYouWantToPresent[row] 
    return item.text 
} " 
But we need to use 
 let item = itemsThatYouWantToPresent[index], not row. It is correct in Example project but not in documentation.

**Comment by filipealva** [comment]
Hello 

Well observed! Thank you so much for reporting.

Solved in: #13
