### ISSUE TITLE
Why it calls didSelectRow when i am turning device in hands? 

### ISSUE THREAD

**Issue by D-Link13** [filipealva/PickerView#16]
Noticed that didSelect calls when I take device in hand (no touches) and put it back.

**Comment by D-Link13** [comment]
Can anybody explain me, why the device rotations may cause calling delegate and datasource methods or even disappearing pickerview from screen?

**Comment by filipealva** [comment]
@D-Link13 It happens because PickerView reloads itself to adapt to new screen orientations.
