### ISSUE TITLE
Swift 3.0 usage

### ISSUE THREAD

**Issue by D-Link13** [filipealva/PickerView#20]
Any restrictions in using this within swift 3.0 project?

**Comment by michaelschwinges** [comment]
I am using it successfully, wonderful project and I'm very grateful for it. I am using the release Xcode 8.1 with Swift 3.

**Comment by D-Link13** [comment]
Converting to swift 3 from pod has no good effect for me =( Can you give me some advice to make it correct?

**Comment by filipealva** [comment]
@michaelschwinges I'm happy you are using it successfully :D 

@D-Link13 Just make sure you are using the `0.3.0` version of `PickerView`. 

You can force installing this version by adding it next to `PickerView` in your Podfile, that way:

`pod 'PickerView', '~> 0.3.0'`

Or running `pod repo update` command, then CocoaPods will update it to the last version (if there is not another version specified after the name of the pod).

**Comment by D-Link13** [comment]
Guess it was all about "Use swift legacy" issue. For now it works fine. Thanks!
