### ISSUE TITLE
Infinite List on iOS 11

### ISSUE THREAD

**Issue by dhruveonmars** [filipealva/PickerView#31]
On iOS 11, an infinite list does not show the selected item anymore, and pressing on items does a really long scroll to the item.

This happens even on the example project included.

**Comment by filipealva** [comment]
The same problem as [this](https://github.com/filipealva/PickerView/issues/30)

I'll release a fix today.

**Comment by dhruveonmars** [comment]
Thanks!

**Comment by dhruveonmars** [comment]
Hey @filipealva, did you manage to get the fix released?

**Comment by filipealva** [comment]
@DhruveShah sorry about the delay, the new version is released 

Please, let me know if everything is working properly

**Comment by dhruveonmars** [comment]
That worked! Thanks a lot!!
