### ISSUE TITLE
`reloadPickerView()` Acting Weird

### ISSUE THREAD

**Issue by niazoff** [filipealva/PickerView#37]
I'm using with iOS 11 and Xcode 9 and when `reloadPickerView()` seems to be called my `pickerView` starts to act strange. The selection is off center from the overlay I have on with the standard style and my conditions for `highlighted` aren't met. Everything seems to get shifted up in position also.

**Comment by filipealva** [comment]
It seems to be related to the way iOS 11 deals with `estimatedRowHeight`.

I already found a workaround for this issue but it makes the PickerView drop some frames, I'll keep trying, and notify you about any news.

**Comment by filipealva** [comment]
Hey @niazoff 

Just fixed this issue. I know it has been a long time, but if you could test it would be awesome. Please points to `https://github.com/filipealva/PickerView/tree/fix/select-row-issues` in your Podfile.

**Comment by niazoff** [comment]
Cool thanks!
