### ISSUE TITLE
Build failed: "No such module 'PickerView' in ExamplePickerViewController.swift

### ISSUE THREAD

**Issue by deyuw** [filipealva/PickerView#39]
Hi Filipe, I want to use your custom picker view on an iOS app I designed. I tried to build your app (Swift 3.2, Xcode 9.1) and there was a Swift Compiler Error saying No Such Module 'PickerView' in ExamplePickerViewController.swift

<img width="597" alt="screen shot 2017-12-21 at 2 54 01 pm" src="https://user-images.githubusercontent.com/5565393/34272658-17f535fc-e65f-11e7-8821-ef57f20219db.png">

Sorry, I'm a bit new to iOS development and I feel like I'm not doing something right. Do you know what the problem is?

**Comment by filipealva** [comment]
Hi @deyuw, 

I bet it have something to do with your project's configuration. 

Hope you have solved it.
