### ISSUE TITLE
Feature request - add support for cell contents to be a view

### ISSUE THREAD

**Issue by michaelschwinges** [filipealva/PickerView#4]
Hi, would you consider adding support for row contents to be a UIView instead of a text label? Thank you for writing PickerView.

**Comment by filipealva** [comment]
Hello Michael,

Thanks for getting in touch.

Yes, I've considered to do that, but I've considered implementing a lot of features that I was not sure if people would use it. So I decided to launch this first version and wait for the community feedback and here it is! hehe

I will convert your issue to `enhancement`, add it as a TODO item on the project and implement as soon as possible.

Again, thank you opening it.

**Comment by michaelschwinges** [comment]
You are very kind for responding so quickly. I googled and looked for ages and yours is the only one that I could find that extends UIListView to work like UIPickerView without the stupid 3D perspective carousel effect. 

Attached is a pic of what I'm trying to achieve, so since your class doesn't do components, I plan to use two side by side.

Thank you again :-)

![img](https://cloud.githubusercontent.com/assets/11598368/11891093/e23ffe26-a563-11e5-8567-cb12ca7ac298.PNG)

**Comment by filipealva** [comment]
Hahah the 3D perspetive carousel effect is on the roadmap, but relax: It will be optional :P 

I can't see the pic of your pickerview, I think you should attach it here through Github instead of e-mail.

**Comment by filipealva** [comment]
#6

**Comment by filipealva** [comment]
Solved with the merge of #6.. Soon I'll make it available through Cocoapods

**Comment by filipealva** [comment]
@michaelschwinges Just released version `0.2.0` which supports a Custom View as a item on PickerView.
