### ISSUE TITLE
Objective.c version

### ISSUE THREAD

**Issue by alfio86** [filipealva/PickerView#7]
This project is amazing! It's very cool believe me!
Maybe is possible have a version in objective.c or a demo project how to implement swift in objective.c?Many now use swift but I'm not so quick to learn😩

Thanks!

**Comment by filipealva** [comment]
Hello @alfio86, thank you so much, your eulogy is very important for me :)

Happily we've implemented Objective-C compatibility with the merge of #6. I have one more feature to implement and very soon this new version will be available through Cocoapods.

Thanks!

**Comment by alfio86** [comment]
Hello @filipealva
Thanks for your reply. Believe me your project is really amazing!
Sorry I did not see the merge #6.
I'm looking forward to try the version in objective.c.
Thank you again

**Comment by alfio86** [comment]
Hi @filipealva 
how evolving the objective.c version?
I hope to try it soon.
Thanks!

**Comment by lfarah** [comment]
Hey @alfio86, I'm asking some friends if they wanna do it.
I strongly suggest you to learn Swift. I'm an ex-Objective-C dev who migrated when Swift launched.
All the new libraries are in Swift, so it is really difficult for Obj-C devs to ignore Swift for that long.

**Comment by alfio86** [comment]
Hi,
Learn Swift is the future I know! But convert all the code you must know swift really well!
I really appreciate if you can help me this time! Thanks!

**Comment by filipealva** [comment]
@alfio86 Just released the version `0.2.0` supporting Objective-C. 

Please, check it out, I'm looking for feedbacks of this update.
