### ISSUE TITLE
Need to scroll pickerView to see updated values.

### ISSUE THREAD

**Issue by TheSlenderMan** [filipealva/PickerView#9]
Whenever I update the list of values I want in the PickerView I have to scroll the current value out of view before they update.

I'm changing the PresentationType to updater the list, is this correct or am I missing something?

**Comment by filipealva** [comment]
@TheSlenderMan Thanks for reaching out and sorry about the delay.

To be honest when I initially wrote it I didn't need to show "mutable" items, so I don't think it supports a "reload" on the go. 

I will make some tests to verify if it is possible and if it is not this will be a feature request, ok?

**Comment by leotumwattana** [comment]
Hi @filipealva,

I'd like this too. My use case is to have one Month picker and one Day picker. Since each month has a different number of days, it'd make sense for the Day picker to change the number of items available.

So please take this as a +1 to this feature request as well. Thanks!

**Comment by filipealva** [comment]
This feature was implemented in the last release `0.3.1`.
